import { useTranslation } from 'react-i18next';
import React,{useEffect,useState} from 'react';

import axios from 'axios';
import {Card} from 'primereact/card';import {InputText} from 'primereact/inputtext';import {Dropdown} from 'primereact/dropdown';import {Button} from 'primereact/button';import {DataTable} from 'primereact/datatable';import {Column} from 'primereact/column';import {Message} from 'primereact/message';

export default function ExpedicoesEstoque(){
 const { t } = useTranslation();
    const[depositos,setDepositos]=useState([]),[depositoId,setDepositoId]=useState(null),[pedidoVendaId,setPedidoVendaId]=useState(''),[rows,setRows]=useState([]),[items,setItems]=useState({}),[error,setError]=useState('');
const load=()=>axios.get('/api/estoque/expedicoes').then(r=>setRows(r.data||[])).catch(e=>setError(e.response?.data?.message||t('legacyUi.expedicoes.loadError')));
useEffect(()=>{axios.get('/api/estoque/depositos').then(r=>{setDepositos(r.data||[]);if(r.data?.length)setDepositoId(r.data[0].id)});load()},[]);
const abrir=async()=>{try{setError('');await axios.post('/api/estoque/expedicoes',{pedidoVendaId:Number(pedidoVendaId),depositoId});setPedidoVendaId('');load()}catch(e){setError(e.response?.data?.message||'Falha ao abrir expedição')}};
const showItems=async id=>{try{const r=await axios.get('/api/estoque/expedicoes/'+id+'/itens');setItems(x=>({...x,[id]:r.data||[]}));}catch(e){setError(e.response?.data?.message||'Falha ao carregar itens')}};
const action=async(id,p)=>{try{await axios.post('/api/estoque/expedicoes/'+id+'/'+p);load();showItems(id)}catch(e){setError(e.response?.data?.message||'Falha na operação')}};
const actions=r=><div className="flex gap-2"><Button icon="pi pi-box" text tooltip="Separar" disabled={r.status!=='ABERTA'} onClick={()=>action(r.id,'separar')}/><Button icon="pi pi-inbox" text tooltip="Embalar" disabled={r.status!=='SEPARACAO'} onClick={()=>action(r.id,'embalar')}/><Button icon="pi pi-send" text tooltip="Expedir" disabled={r.status!=='EMBALAGEM'} onClick={()=>action(r.id,'expedir')}/></div>;
return <Card title={t('legacyUi.expedicoes.title')}><div className="p-fluid grid"><div className="field col-12 md:col-3"><label>Pedido de venda ID</label><InputText value={pedidoVendaId} onChange={e=>setPedidoVendaId(e.target.value)}/></div><div className="field col-12 md:col-3"><label>Depósito</label><Dropdown value={depositoId} options={depositos} optionLabel="nome" optionValue="id" onChange={e=>setDepositoId(e.value)}/></div><div className="col-12 md:col-3 flex align-items-end"><Button label={t('legacyUi.expedicoes.ship')} icon="pi pi-plus" onClick={abrir} disabled={!pedidoVendaId||!depositoId}/></div></div>{error&&<Message severity="error" text={error}/>}<DataTable value={rows} paginator rows={10} stripedRows className="mt-3"><Column field="id" header="Expedição"/><Column field="pedidoVendaId" header="Pedido"/><Column field="depositoId" header="Depósito"/><Column field="status" header="Status"/><Column field="dataAbertura" header="Abertura"/><Column field="id" header="Itens" body={r=><Button icon="pi pi-list" text tooltip="Ver itens" onClick={()=>showItems(r.id)}/>} /><Column header="Fluxo" body={actions}/></DataTable>{Object.entries(items).map(([id,its])=><div key={id} className="mt-3"><h4>Itens da expedição #{id}</h4><DataTable value={its} size="small"><Column field="produtoId" header="Produto"/><Column field="loteId" header="Lote"/><Column field="quantidade" header="Quantidade"/><Column field="status" header="Status"/></DataTable></div>)}</Card>}