import { useTranslation } from 'react-i18next';
import React,{useEffect,useRef,useState} from 'react';

import {Card} from 'primereact/card'; import {DataTable} from 'primereact/datatable'; import {Column} from 'primereact/column';
import {Button} from 'primereact/button'; import {Dropdown} from 'primereact/dropdown'; import {AutoComplete} from 'primereact/autocomplete';
import {InputNumber} from 'primereact/inputnumber'; import {InputTextarea} from 'primereact/inputtextarea'; import {Toast} from 'primereact/toast'; import axios from 'axios'; import ProdutoService from '../../services/ProdutoService';

const msg=e=>e?.response?.data?.errors?.[0]?.message||e?.response?.data?.message||e?.message||'Operação não realizada';
export default function InventariosEstoque(){
 const { t } = useTranslation();
    
 const toast=useRef(null),[depositos,setDepositos]=useState([]),[rows,setRows]=useState([]),[inv,setInv]=useState(null),[itens,setItens]=useState([]),[produto,setProduto]=useState(null),[sug,setSug]=useState([]),[qtd,setQtd]=useState(0),[obs,setObs]=useState(''),[enderecoId,setEnderecoId]=useState(null),[enderecos,setEnderecos]=useState([]),[loteId,setLoteId]=useState(null),[lotes,setLotes]=useState([]);
 const load=async()=>{try{const [d,i]=await Promise.all([axios.get('/api/estoque/depositos'),axios.get('/api/estoque/inventarios')]);setDepositos(d.data?.data??d.data??[]);setRows(i.data?.data??i.data??[])}catch(e){toast.current?.show({severity:'error',summary:'Erro',detail:msg(e),life:4000})}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!inv?.depositoId)return;axios.get('/api/estoque/enderecos',{params:{depositoId:inv.depositoId}}).then(r=>setEnderecos(r.data||[]));},[inv]);
 useEffect(()=>{if(!inv||!produto?.id)return;axios.get('/api/estoque/lotes',{params:{produtoId:produto.id,depositoId:inv.depositoId}}).then(r=>setLotes((r.data||[]).filter(x=>x.status==='ATIVO'))).catch(()=>setLotes([]));},[inv,produto]);
 const search=async e=>{if(!e.query)return setSug([]);try{const r=await ProdutoService.buscarPorNome(e.query,0,20);const d=r.data?.data?.content??r.data?.content??r.data?.data??r.data??[];setSug(Array.isArray(d)?d:[])}catch{setSug([])}};
 const criar=async()=>{if(!inv?.depositoId)return toast.current?.show({severity:'warn',summary:'Inventário',detail:t('legacyUi.inventarios.warehouseRequired'),life:3000});try{const r=await axios.post('/api/estoque/inventarios',{depositoId:inv.depositoId,observacoes:obs});setInv(r.data);setItens([]);setObs('');load()}catch(e){toast.current?.show({severity:'error',summary:'Erro',detail:msg(e),life:5000})}};
 const selecionar=async i=>{setInv(i);try{const r=await axios.get('/api/estoque/inventarios/'+i.id+'/itens');setItens(r.data||[])}catch(e){toast.current?.show({severity:'error',summary:'Erro',detail:msg(e),life:4000})}};
 const contar=async()=>{if(!inv||!produto?.id||qtd<0)return toast.current?.show({severity:'warn',summary:'Contagem',detail:t('legacyUi.inventarios.countRequired'),life:3000});try{await axios.post('/api/estoque/inventarios/'+inv.id+'/contagens',{produtoId:produto.id,loteId:loteId||null,enderecoId:enderecoId||null,quantidadeContada:qtd,observacao:obs});await selecionar(inv);setProduto(null);setQtd(0);setLoteId(null);setEnderecoId(null);setObs('')}catch(e){toast.current?.show({severity:'error',summary:'Erro',detail:msg(e),life:5000})}};
 const fechar=async()=>{try{const r=await axios.post('/api/estoque/inventarios/'+inv.id+'/fechar');setInv(r.data);await load();toast.current?.show({severity:'success',summary:'Inventário',detail:t('legacyUi.inventarios.closed'),life:4000})}catch(e){toast.current?.show({severity:'error',summary:'Erro',detail:msg(e),life:5000})}};
 return <div><Toast ref={toast}/><Card title={t('legacyUi.inventarios.title')}>
 <div className="grid p-fluid"><div className="col-12 md:col-4 field"><label>Depósito</label><Dropdown value={inv?.depositoId} options={depositos.map(d=>({label:d.codigo+' — '+d.nome,value:d.id}))} onChange={e=>setInv(x=>x?.id?x:{depositoId:e.value})} placeholder="Selecione"/></div><div className="col-12 md:col-4 field"><label>Observações</label><InputTextarea value={obs} rows={1} onChange={e=>setObs(e.target.value)}/></div><div className="col-12 md:col-4 field"><label>&nbsp;</label><Button label={t('legacyUi.inventarios.open')} icon="pi pi-plus" onClick={criar}/></div></div>
 <DataTable value={rows} size="small" paginator rows={8} selectionMode="single" onSelectionChange={e=>selecionar(e.value)}><Column field="id" header="#"/><Column field="depositoId" header="Depósito"/><Column field="status" header="Status"/><Column field="dataContagem" header="Data"/></DataTable>
 {inv&&<Card title={'Contagem #'+inv.id} className="mt-3"><div className="grid p-fluid"><div className="col-12 md:col-4 field"><label>Produto *</label><AutoComplete value={produto} suggestions={sug} completeMethod={search} field="nome" onChange={e=>setProduto(e.value)} placeholder="Nome ou código"/></div><div className="col-12 md:col-2 field"><label>Lote</label><Dropdown value={loteId} options={lotes} optionLabel="codigo" optionValue="id" onChange={e=>setLoteId(e.value)} placeholder="Opcional"/></div><div className="col-12 md:col-2 field"><label>Endereço</label><Dropdown value={enderecoId} options={enderecos.map(e=>({label:e.codigo,value:e.id}))} onChange={e=>setEnderecoId(e.value)} placeholder="Opcional"/></div><div className="col-12 md:col-2 field"><label>Quantidade contada</label><InputNumber value={qtd} min={0} minFractionDigits={3} onValueChange={e=>setQtd(e.value||0)}/></div><div className="col-12 md:col-2 field"><label>&nbsp;</label><Button label="Registrar" onClick={contar} disabled={inv.status!=='ABERTO'}/></div></div>
 <DataTable value={itens} size="small"><Column field="produtoId" header="Produto"/><Column field="loteId" header="Lote"/><Column field="enderecoId" header="Endereço"/><Column field="quantidadeSistema" header="Sistema"/><Column field="quantidadeContada" header="Contado"/><Column field="diferenca" header="Diferença"/></DataTable>
 <div className="mt-3"><Button label={t('legacyUi.inventarios.close')} icon="pi pi-check" severity="warning" onClick={fechar} disabled={inv.status!=='ABERTO'||!itens.length}/></div></Card>}
 </Card></div>;
}