import React,{useEffect,useState} from 'react';
import { useTranslation } from 'react-i18next';

import axios from 'axios';
import {Card} from 'primereact/card'; import {Dropdown} from 'primereact/dropdown'; import {InputText} from 'primereact/inputtext'; import {InputNumber} from 'primereact/inputnumber'; import {Button} from 'primereact/button'; import {DataTable} from 'primereact/datatable'; import {Column} from 'primereact/column'; import {Message} from 'primereact/message';
import {AutoComplete} from 'primereact/autocomplete';
import ProdutoService from '../../services/ProdutoService';

export default function ReservasEstoque(){const { t } = useTranslation(); const [depositos,setDepositos]=useState([]);const [depositoId,setDepositoId]=useState(null);const [produtoId,setProdutoId]=useState('');const [produto,setProduto]=useState(null);const [produtos,setProdutos]=useState([]);const [pedidoVendaId,setPedidoVendaId]=useState('');const [loteId,setLoteId]=useState(null);const [lotes,setLotes]=useState([]);const [enderecoId,setEnderecoId]=useState(null);const [enderecos,setEnderecos]=useState([]);const [enderecosDisponiveis,setEnderecosDisponiveis]=useState([]);const [quantidade,setQuantidade]=useState(1);const [rows,setRows]=useState([]);const [error,setError]=useState('');
const load=async()=>{const r=await axios.get('/api/estoque/reservas');setRows(r.data||[])};useEffect(()=>{axios.get('/api/estoque/depositos').then(r=>{setDepositos(r.data||[]);if(r.data?.length){setDepositoId(r.data[0].id);}});load().catch(e=>setError(e.response?.data?.message||'Falha ao carregar reservas'));},[]);
useEffect(()=>{if(!depositoId){setEnderecos([]);return;}axios.get('/api/estoque/enderecos',{params:{depositoId}}).then(r=>setEnderecos(r.data||[])).catch(()=>setEnderecos([]));},[depositoId]);
const carregarEnderecos=async(id,lote)=>{if(!id||!depositoId){setEnderecosDisponiveis([]);return;}try{const r=await axios.get('/api/estoque/reservas/picking-sugestoes',{params:{depositoId,produtoId:id,...(lote?{loteId:lote}:{})}});const ids=new Set((r.data||[]).filter(x=>Number(x.quantidade)>0).map(x=>x.enderecoId));setEnderecosDisponiveis(enderecos.filter(e=>ids.has(e.id)));}catch{setEnderecosDisponiveis([])}};
useEffect(()=>{if(produtoId)carregarEnderecos(produtoId,loteId);},[produtoId,loteId,depositoId,enderecos]);
const carregarLotes=async id=>{if(!id){setLotes([]);setLoteId(null);setEnderecoId(null);setEnderecosDisponiveis([]);return;}try{const r=await axios.get('/api/estoque/lotes',{params:{produtoId:id,depositoId}});setLotes((r.data||[]).filter(x=>x.status==='ATIVO'));setEnderecoId(null);}catch{setLotes([]);}};
const buscarProdutos=async e=>{try{const r=await ProdutoService.buscarPorNome((e.query||'').trim(),0,20);const d=r?.data?.data?.content??r?.data?.content??r?.data?.data??r?.data??[];setProdutos(Array.isArray(d)?d:[])}catch{setProdutos([])}};
const save=async()=>{try{setError('');await axios.post('/api/estoque/reservas',{depositoId,produtoId:Number(produtoId),pedidoVendaId:pedidoVendaId?Number(pedidoVendaId):null,loteId:loteId||null,enderecoId:enderecoId||null,quantidade});load();}catch(e){setError(e.response?.data?.message||'Falha ao reservar estoque');}};
const action=async(id,path)=>{try{await axios.post('/api/estoque/reservas/'+id+'/'+path);load();}catch(e){setError(e.response?.data?.message||'Falha na operação');}};
return <Card title={t('legacyUi.reservas.title')}><div className="p-fluid grid"><div className="field col-12 md:col-2"><label>Depósito</label><Dropdown value={depositoId} options={depositos} optionLabel="nome" optionValue="id" onChange={e=>setDepositoId(e.value)}/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.product')}</label><AutoComplete value={produto} suggestions={produtos} completeMethod={buscarProdutos} itemTemplate={p=><div><strong>{p.nome||p.descricao}</strong><small className="ml-2">{p.codigo||p.id}</small></div>} selectedItemTemplate={p=>p?`${p.nome||p.descricao} · ${p.codigo||p.id}`:''} onChange={e=>{setProduto(e.value);setProdutoId(e.value?.id||'');carregarLotes(e.value?.id)}} placeholder="Pesquisar produto"/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.lot')}</label><Dropdown value={loteId} options={lotes} optionLabel="codigo" optionValue="id" onChange={e=>setLoteId(e.value)} placeholder="FEFO / lote"/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.address')}</label><Dropdown value={enderecoId} options={enderecosDisponiveis} optionLabel="codigo" optionValue="id" onChange={e=>setEnderecoId(e.value)} placeholder="FEFO / endereço"/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.address')}</label><Dropdown value={enderecoId} options={enderecosDisponiveis} optionLabel="codigo" optionValue="id" onChange={e=>setEnderecoId(e.value)} placeholder="FEFO / endereço"/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.order')}</label><InputText value={pedidoVendaId} onChange={e=>setPedidoVendaId(e.target.value)}/></div><div className="field col-12 md:col-2"><label>{t('legacyUi.reservas.quantity')}</label><InputNumber value={quantidade} onValueChange={e=>setQuantidade(e.value||1)} minFractionDigits={3}/></div><div className="col-12 md:col-2 flex align-items-end"><Button label={t('legacyUi.reservas.save')} icon="pi pi-lock" onClick={save} disabled={!depositoId||!produtoId}/></div></div>{error&&<Message severity="error" text={error}/>}<DataTable value={rows} className="mt-3" paginator rows={10} stripedRows><Column field="pedidoVendaId" header="Pedido"/><Column field="produtoId" header="Produto"/><Column field="loteId" header="Lote"/><Column field="enderecoId" header="Endereço"/><Column field="depositoId" header="Depósito"/><Column field="quantidade" header="Qtd."/><Column field="status" header="Status"/><Column header="Ações" body={r=><div className="flex gap-2"><Button icon="pi pi-box" text tooltip={t('legacyUi.reservas.separate')} onClick={()=>action(r.id,'separar')} disabled={r.status!=='RESERVADA'}/><Button icon="pi pi-unlock" text tooltip={t('legacyUi.reservas.release')} onClick={()=>action(r.id,'liberar')} disabled={!['RESERVADA','SEPARACAO'].includes(r.status)}/></div>}/></DataTable></Card>}