-- Complemento FI-AA/PM do PR #38. Preserva V129 e todas as migrations históricas.
-- Não altera dados, não recria tabelas legadas e não marca migrations como aplicadas.

ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS classe_id bigint;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS centro_custo_id bigint;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS fornecedor_id bigint;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS numero_documento varchar(60);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS data_inicio_depreciacao date;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS metodo_depreciacao varchar(30);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS taxa_anual numeric(7,4);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS ativo_pai_id bigint;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS fabricante varchar(120);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS modelo varchar(120);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS garantia_ate date;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS valor_reavaliacao numeric(15,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS valor_impairment numeric(15,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS data_baixa date;
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS valor_baixa numeric(15,2);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS motivo_baixa varchar(500);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS ultimo_periodo_depreciado varchar(7);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS contador_atual numeric(15,2);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS unidade_contador varchar(20);
ALTER TABLE brasil_saas.bc_ativo_imobilizado ADD COLUMN IF NOT EXISTS critico boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_movimento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    ativo_id bigint NOT NULL,
    tipo varchar(30) NOT NULL,
    data_movimento date NOT NULL,
    periodo varchar(7) NOT NULL,
    valor numeric(15,2) NOT NULL DEFAULT 0,
    valor_depreciacao numeric(15,2) NOT NULL DEFAULT 0,
    valor_venda numeric(15,2),
    resultado numeric(15,2),
    execucao_id bigint,
    lancamento_id bigint,
    centro_custo_origem_id bigint,
    centro_custo_destino_id bigint,
    localizacao_origem varchar(255),
    localizacao_destino varchar(255),
    responsavel_origem_id bigint,
    responsavel_destino_id bigint,
    documento varchar(60),
    observacao varchar(1000),
    status varchar(20) NOT NULL DEFAULT 'ATIVO',
    usuario_id bigint
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_movimento_empresa ON brasil_saas.bc_ativo_movimento(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_classe (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    codigo varchar(30) NOT NULL,
    descricao varchar(255) NOT NULL,
    metodo_depreciacao varchar(30) NOT NULL DEFAULT 'LINEAR',
    vida_util_meses integer,
    taxa_anual numeric(7,4),
    conta_ativo_id bigint,
    conta_depreciacao_acumulada_id bigint,
    conta_despesa_depreciacao_id bigint,
    conta_ganho_baixa_id bigint,
    conta_perda_baixa_id bigint,
    conta_reavaliacao_id bigint,
    conta_impairment_id bigint,
    ativo boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_classe_empresa ON brasil_saas.bc_ativo_classe(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_depreciacao_execucao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    periodo varchar(7) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'EFETIVADA',
    quantidade_ativos integer NOT NULL DEFAULT 0,
    valor_total numeric(15,2) NOT NULL DEFAULT 0,
    valor_contabilizado numeric(15,2) NOT NULL DEFAULT 0,
    lancamento_id bigint,
    usuario_id bigint,
    estornada_em timestamp
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_depreciacao_execucao_empresa ON brasil_saas.bc_ativo_depreciacao_execucao(empresa_id) WHERE deleted_at IS NULL;

ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS plano_id bigint;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS nota_id bigint;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS data_inicio date;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS horas_trabalhadas numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS horas_parada numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS custo_material numeric(15,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS custo_mao_obra numeric(15,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS custo_servico numeric(15,2) NOT NULL DEFAULT 0;
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS causa varchar(1000);
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS solucao varchar(2000);
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS checklist varchar(4000);
ALTER TABLE brasil_saas.bc_ativo_manutencao ADD COLUMN IF NOT EXISTS centro_custo_id bigint;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_manutencao_apontamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    manutencao_id bigint NOT NULL,
    funcionario_id bigint,
    data_apontamento date NOT NULL,
    horas numeric(10,2) NOT NULL DEFAULT 0,
    custo_hora numeric(15,2) NOT NULL DEFAULT 0,
    custo_total numeric(15,2) NOT NULL DEFAULT 0,
    descricao varchar(1000)
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_manutencao_apontamento_empresa ON brasil_saas.bc_ativo_manutencao_apontamento(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_manutencao_material (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    manutencao_id bigint NOT NULL,
    produto_id bigint,
    descricao varchar(255) NOT NULL,
    quantidade numeric(15,4) NOT NULL DEFAULT 0,
    custo_unitario numeric(15,4) NOT NULL DEFAULT 0,
    custo_total numeric(15,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_manutencao_material_empresa ON brasil_saas.bc_ativo_manutencao_material(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_medicao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    ativo_id bigint NOT NULL,
    data_medicao date NOT NULL,
    valor numeric(15,2) NOT NULL,
    unidade varchar(20),
    observacao varchar(500)
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_medicao_empresa ON brasil_saas.bc_ativo_medicao(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_nota_manutencao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    ativo_id bigint NOT NULL,
    numero varchar(50) NOT NULL,
    tipo varchar(30) NOT NULL DEFAULT 'AVARIA',
    prioridade varchar(20) NOT NULL DEFAULT 'MEDIA',
    status varchar(30) NOT NULL DEFAULT 'ABERTA',
    descricao varchar(2000) NOT NULL,
    sintoma varchar(1000),
    causa varchar(1000),
    equipamento_parado boolean NOT NULL DEFAULT false,
    inicio_parada timestamp,
    fim_parada timestamp,
    data_nota date NOT NULL,
    manutencao_id bigint,
    solicitante_id bigint
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_nota_manutencao_empresa ON brasil_saas.bc_ativo_nota_manutencao(empresa_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS brasil_saas.bc_ativo_plano_manutencao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    empresa_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    deleted_at timestamp,
    ativo_id bigint NOT NULL,
    codigo varchar(30) NOT NULL,
    descricao varchar(255) NOT NULL,
    tipo_ciclo varchar(20) NOT NULL DEFAULT 'TEMPO',
    intervalo_dias integer,
    intervalo_contador numeric(15,2),
    antecedencia_dias integer NOT NULL DEFAULT 0,
    ultima_execucao date,
    contador_ultima_execucao numeric(15,2),
    proxima_data date,
    checklist varchar(4000),
    horas_estimadas numeric(10,2),
    custo_estimado numeric(15,2),
    prioridade varchar(20) NOT NULL DEFAULT 'MEDIA',
    responsavel_id bigint,
    ativo boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS ix_bc_ativo_plano_manutencao_empresa ON brasil_saas.bc_ativo_plano_manutencao(empresa_id) WHERE deleted_at IS NULL;

